### ISSUE TITLE
crashed after connecting pipes

### ISSUE THREAD

**Issue by SDUBZ** [grondag/facility#1]
https://paste.ee/p/CizSf

**Comment by grondag** [comment]
Thank you for the report. Looks like one of the blocks was a creative crate. What was the other block and did the creative crate have a red stone signal going into it? (Guessing it did, otherwise it shouldn’t have tried to generate an item.)

**Comment by SDUBZ** [comment]
it was hooked upto the 4x4 block and single slot ones
was testing
