### ISSUE TITLE
Rough Enough Items (REI) Crash 

### ISSUE THREAD

**Issue by PROJonYz** [grondag/facility#11]
Facility mod crashes REI when you're scrolling list down, is there any chance to fix that issue?

![Screenshot_3](https://user-images.githubusercontent.com/67200060/85206605-f397d100-b32b-11ea-888e-82658fa8d4de.png)

**Comment by grondag** [comment]
I need your log.  That will tell me what versions are present and where the crash ocurred.

**Comment by grondag** [comment]
Unable to reproduce

**Comment by Bulldog83** [comment]
I have this crash too.
https://gist.github.com/Bulldog83/0b2197dfedf34e1ae6d2b1915aaa9d80

It caused by the NPE in the Exotic Matter library.

Minecraft 1.16.1
Facility 0.9.147

**Comment by grondag** [comment]
@Bulldog83 That crash is caused by incompatibility with Sodium. Sodium does not yet support the Fabric Rendering API.
