### ISSUE TITLE
Critical item duplication glitch

### ISSUE THREAD

**Issue by Cydhra** [grondag/facility#18]
1. place any crate in the world
2. put any items in it
3. keep the GUI of the crate open, while a second player breaks the crate
4. now drop every item out of the GUI into the world, while the second player has the crate in their inventory.

You now have successfully duplicated the items.
It's a pretty common duplication glitch, so the solutions are well-known:

Either close the GUI when the crate is broken (probably the most straight-forward solution, because there is no reason for it to stay open anyway).
Or directly map all events in the GUI into the crate without caching the crate reference anywhere in the containers. If the crate is unavailable in the world, cancel all events.

Tested on: facility-mc116-0.9.147

**Comment by grondag** [comment]
Fixed in next release
