### ISSUE TITLE
Game crashes on trying to search for Facility items in recipe book

### ISSUE THREAD

**Issue by G93d14** [grondag/facility#19]
hey, the game crashes if I search for any of your items in the vanilla recipe book. I don't know if it's because I'm playing on a potato, but here's the crash log anyhow ([paste.ee link](https://paste.ee/p/iW6mC)).

**Comment by G93d14** [comment]
[crash-2020-07-30_18.32.49-client.txt](https://github.com/grondag/facility/files/5001369/crash-2020-07-30_18.32.49-client.txt)
[crash-2020-07-30_18.27.55-client.txt](https://github.com/grondag/facility/files/5001370/crash-2020-07-30_18.27.55-client.txt)
[crash-2020-07-30_18.30.01-client.txt](https://github.com/grondag/facility/files/5001371/crash-2020-07-30_18.30.01-client.txt)

here are the crash reports too.

**Comment by G93d14** [comment]
It seems to be an issue with either your mod, or the way your mod interacts with Sodium, from what I can tell.

**Comment by grondag** [comment]
Sodium currently does not support the Fabric Rendering API, which Facility uses heavily, so yeah, it can't work.  I believe support is planned.

Until then, you can try [Canvas](https://www.curseforge.com/minecraft/mc-mods/canvas-renderer) as an upgrade to the Indigo renderer included with Fabric API, but it will not be as fast as Sodium on most hardware.

I will be adding metadata to make this incompatibility clear at start-up.

**Comment by G93d14** [comment]
Hmm... I guess I'll have to find a different mass storage mod then, until
Sodium manages to work with Fabric Rendering API. Thanks for responding so
quickly!
