### ISSUE TITLE
blocks and interaction(testing)

### ISSUE THREAD

**Issue by SDUBZ** [grondag/facility#2]
creative bins break trying to interact with display face
also came across this why trying to input to creative 4x4 bins
https://paste.ee/p/zEKY3 
plus
https://cdn.discordapp.com/attachments/507982463449169932/665390385220288537/unknown.png

this seems to happen with all of them
nothing is going over a stack

**Comment by SDUBZ** [comment]
can insert to bins/crates via inserters and other hopper like methods

**Comment by grondag** [comment]
Unable to duplicate in latest build.
