### ISSUE TITLE
Add an extremely large crate

### ISSUE THREAD

**Issue by haykam821** [grondag/facility#3]
Having a crate with a very large size (preferably the maximum limit that the system allows) would be useful for players who do not want to worry about storage.

**Comment by grondag** [comment]
It would be easy to do but what would the recipe be like?  Should it just be a creative item and pack makers create a recipe for it?

**Comment by haykam821** [comment]
Making a recipe through a global data pack would be fine, though unlike a recipe-less creative item I think it should have the brown texture as it is more of a useful block than a debugging tool. Don't know about the name/identifier though, unless Infinite Crate is fine.

**Comment by grondag** [comment]
Will be in next release, no recipe.
