### ISSUE TITLE
20w06a item attributes flush whenever crate is in inventory

### ISSUE THREAD

**Issue by JillyRabbit** [grondag/facility#5]
if you have a crate placed somewhere in the world, breaking and picking it up will reset all damage values, NBT data, etc. of items within it. (all potions become Uncraftable Potion for instance)

if the crate is used from your inventory, the same thing happens as soon as you close the interface

**Comment by grondag** [comment]
That's pretty bad.  Thank you for the report.  Will look into it.

**Comment by grondag** [comment]
Fixed in https://github.com/grondag/fluidity/commit/a1237f9f49ec547d0bca923f1a67bb6eef9b6e1b

Build will be on Curse in a little bit.
