### ISSUE TITLE
Tank crash 

### ISSUE THREAD

**Issue by Dragonracer1973** [grondag/facility#6]
[crash-2020-02-16_15.40.40-server.txt](https://github.com/grondag/facility/files/4210968/crash-2020-02-16_15.40.40-server.txt)
This was just before your update so maybe its fixed now?

**Comment by grondag** [comment]
Thank you for the report.  Will take a look.

**Comment by grondag** [comment]
Do you remember what was in the tank?

**Comment by Dragonracer1973** [comment]
it was empty, was attempting to make a multiblock

**Comment by grondag** [comment]
Unable to duplicate. Have made several improvements in next build that may prevent whatever caused it. Will be on Curse soonish.
