### ISSUE TITLE
Pipes does not connect correctly

### ISSUE THREAD

**Issue by FaultyPixel** [grondag/facility#9]
![2020-04-23_14 28 19](https://user-images.githubusercontent.com/64114112/80099810-5e689e00-856f-11ea-88ba-25ebb0fee11f.png)

This happens in a multiple of cases but it seems that it depends on wich side of the pipes/blocks you are looking at when placing the pipe. 

Also, the following system works, transferring items from the crate on the left to the right.
![2020-04-23_14 36 42](https://user-images.githubusercontent.com/64114112/80100243-febec280-856f-11ea-9297-68c8cd0901e3.png)

However if you just replace the intake adapter by a straight pipe and vis versa, by shift-right clicking on the crates to place them and keeping the upper pipes you get this :
![2020-04-23_14 39 25](https://user-images.githubusercontent.com/64114112/80100526-59581e80-8570-11ea-9dfa-a2207719b5b2.png)

Additionally, I don't know if the fact that you can only pull from the bottom of a chest intended or not or if other sides from a chest are not yet implemented but anyway, you also get this configuration when placing straight pipes on a flexible one directly connected to an intake.

![2020-04-23_14 46 20](https://user-images.githubusercontent.com/64114112/80101619-f2d40000-8571-11ea-8c63-fa6fa20cc207.png)

I am using Minecraft 1.15.2 and Facility 0.7.118

If I wasn't clear enough please forgive me as english is not my native language. Anyway, I absolutely love your mod ! Thank you !

**Comment by grondag** [comment]
Thank you.  Updating Facility to 1.16 and will try to reproduce/fix these.

**Comment by grondag** [comment]
Not able to reproduce these in most recent 1.16.1 build.
